
# Script to calculate synteny stats (Supplementary table 5)
# use as input leptidea_synteny_data.txt, generated by script 'quantify_synteny.sh'

setwd("~/Desktop/Plots")

df <- read.csv("leptidea_synteny_data.txt", header = TRUE, sep = "\t")

lj <- df[df$species == "lj", ]
lr <- df[df$species == "lr", ]
ls <- df[df$species == "ls", ]
lc <- df[df$species == "lc", ]

# synteny blocks

lj_synteny_blocks <- nrow(lj[lj$type == "block_sizes", ])
lr_synteny_blocks <- nrow(lr[lr$type == "block_sizes", ])
ls_synteny_blocks <- nrow(ls[ls$type == "block_sizes", ])
lc_synteny_blocks <- nrow(lc[lc$type == "block_sizes", ])

# median synteny blocks / chr

lj_blocks_per_chr <- lj[lj$type == "blocks_per_chr", ]
lj_median_blocks_per_chr <- median(lj_blocks_per_chr$count)

lr_blocks_per_chr <- lr[lr$type == "blocks_per_chr", ]
lr_median_blocks_per_chr <- median(lr_blocks_per_chr$count)

ls_blocks_per_chr <- ls[ls$type == "blocks_per_chr", ]
ls_median_blocks_per_chr <- median(ls_blocks_per_chr$count)

lc_blocks_per_chr <- lc[lc$type == "blocks_per_chr", ]
lc_median_blocks_per_chr <- median(lc_blocks_per_chr$count)

# median bm chr / chr

lj_chr_per_chr <- lj[lj$type == "chr_in_chr", ]
lj_median_chr_per_chr <- median(lj_chr_per_chr$count)

lr_chr_per_chr <- lr[lr$type == "chr_in_chr", ]
lr_median_chr_per_chr <- median(lr_chr_per_chr$count)

ls_chr_per_chr <- ls[ls$type == "chr_in_chr", ]
ls_median_chr_per_chr <- median(ls_chr_per_chr$count)

lc_chr_per_chr <- lc[lc$type == "chr_in_chr", ]
lc_median_chr_per_chr <- median(lc_chr_per_chr$count)

# median block sizes (mb)

lj_block_sizes <- lj[lj$type == "block_sizes", ]
lj_median_block_sizes <- median((lj_block_sizes$count)/1000000)

lr_block_sizes <- lr[lr$type == "block_sizes", ]
lr_median_block_sizes <- median((lr_block_sizes$count)/1000000)

ls_block_sizes <- ls[ls$type == "block_sizes", ]
ls_median_block_sizes <- median((ls_block_sizes$count)/1000000)

lc_block_sizes <- lc[lc$type == "block_sizes", ]
lc_median_block_sizes <- median((lc_block_sizes$count)/1000000)

# genes in synteny blocks

lj_genes_per_block <- lj[lj$type == "genes_per_block", ]
lj_genes_in_blocks <- sum(lj_genes_per_block$count)

lr_genes_per_block <- lr[lr$type == "genes_per_block", ]
lr_genes_in_blocks <- sum(lr_genes_per_block$count)

ls_genes_per_block <- ls[ls$type == "genes_per_block", ]
ls_genes_in_blocks <- sum(ls_genes_per_block$count)

lc_genes_per_block <- lc[lc$type == "genes_per_block", ]
lc_genes_in_blocks <- sum(lc_genes_per_block$count)

# median genes / block

lj_median_genes_per_block <- median(lj_genes_per_block$count)
lr_median_genes_per_block <- median(lr_genes_per_block$count)
ls_median_genes_per_block <- median(ls_genes_per_block$count)
lc_median_genes_per_block <- median(lc_genes_per_block$count)

# orthologs in synteny blocks

lj_orthologs_per_block <- lj[lj$type == "orthologs_per_block", ]
lj_orthologs_in_blocks <- sum(lj_orthologs_per_block$count)

lr_orthologs_per_block <- lr[lr$type == "orthologs_per_block", ]
lr_orthologs_in_blocks <- sum(lr_orthologs_per_block$count)

ls_orthologs_per_block <- ls[ls$type == "orthologs_per_block", ]
ls_orthologs_in_blocks <- sum(ls_orthologs_per_block$count)

lc_orthologs_per_block <- lc[lc$type == "orthologs_per_block", ]
lc_orthologs_in_blocks <- sum(lc_orthologs_per_block$count)

# median orthologs / block

lj_median_orthologs_per_block <- median(lj_orthologs_per_block$count)
lr_median_orthologs_per_block <- median(lr_orthologs_per_block$count)
ls_median_orthologs_per_block <- median(ls_orthologs_per_block$count)
lc_median_orthologs_per_block <- median(lc_orthologs_per_block$count)
